# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: ui_elements/properties/pixel_location.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n+ui_elements/properties/pixel_location.proto\x12\x1d\x61spire.ui_elements.properties\"I\n\rPixelLocation\x12\x0b\n\x03top\x18\x01 \x01(\r\x12\x0e\n\x06\x62ottom\x18\x02 \x01(\r\x12\x0c\n\x04left\x18\x03 \x01(\r\x12\r\n\x05right\x18\x04 \x01(\rb\x06proto3')



_PIXELLOCATION = DESCRIPTOR.message_types_by_name['PixelLocation']
PixelLocation = _reflection.GeneratedProtocolMessageType('PixelLocation', (_message.Message,), {
  'DESCRIPTOR' : _PIXELLOCATION,
  '__module__' : 'ui_elements.properties.pixel_location_pb2'
  # @@protoc_insertion_point(class_scope:aspire.ui_elements.properties.PixelLocation)
  })
_sym_db.RegisterMessage(PixelLocation)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _PIXELLOCATION._serialized_start=78
  _PIXELLOCATION._serialized_end=151
# @@protoc_insertion_point(module_scope)
