# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: legacy.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0clegacy.proto\x12\raspire.legacy\"B\n\x0eWindowsUiaCell\x12\x11\n\ttable_uid\x18\x01 \x01(\t\x12\x0e\n\x06\x63oords\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"0\n\rUpdateRequest\x12\x11\n\ttable_uid\x18\x01 \x01(\t\x12\x0c\n\x04\x64\x61ta\x18\x02 \x01(\t\"Q\n\x0eUpdateResponse\x12\x11\n\ttable_uid\x18\x01 \x01(\t\x12,\n\x05\x63\x65lls\x18\x02 \x03(\x0b\x32\x1d.aspire.legacy.WindowsUiaCell\"%\n\x10UppercaseRequest\x12\x11\n\ttable_uid\x18\x01 \x01(\t\"T\n\x11UppercaseResponse\x12\x11\n\ttable_uid\x18\x01 \x01(\t\x12,\n\x05\x63\x65lls\x18\x02 \x03(\x0b\x32\x1d.aspire.legacy.WindowsUiaCell\"5\n\x0b\x43opyRequest\x12\x12\n\ntable0_uid\x18\x01 \x01(\t\x12\x12\n\ntable1_uid\x18\x02 \x01(\t\"d\n\x0c\x43opyResponse\x12\x12\n\ntable0_uid\x18\x01 \x01(\t\x12\x12\n\ntable1_uid\x18\x02 \x01(\t\x12,\n\x05\x63\x65lls\x18\x03 \x03(\x0b\x32\x1d.aspire.legacy.WindowsUiaCell\":\n\x10\x43opyEventRequest\x12\x12\n\ntable0_uid\x18\x01 \x01(\t\x12\x12\n\ntable1_uid\x18\x02 \x01(\t\"i\n\x11\x43opyEventResponse\x12\x12\n\ntable0_uid\x18\x01 \x01(\t\x12\x12\n\ntable1_uid\x18\x02 \x01(\t\x12,\n\x05\x63\x65lls\x18\x03 \x03(\x0b\x32\x1d.aspire.legacy.WindowsUiaCell2\xaf\x02\n\x05\x42rain\x12\x45\n\x06Update\x12\x1c.aspire.legacy.UpdateRequest\x1a\x1d.aspire.legacy.UpdateResponse\x12N\n\tUppercase\x12\x1f.aspire.legacy.UppercaseRequest\x1a .aspire.legacy.UppercaseResponse\x12?\n\x04\x43opy\x12\x1a.aspire.legacy.CopyRequest\x1a\x1b.aspire.legacy.CopyResponse\x12N\n\tCopyEvent\x12\x1f.aspire.legacy.CopyEventRequest\x1a .aspire.legacy.CopyEventResponseb\x06proto3')



_WINDOWSUIACELL = DESCRIPTOR.message_types_by_name['WindowsUiaCell']
_UPDATEREQUEST = DESCRIPTOR.message_types_by_name['UpdateRequest']
_UPDATERESPONSE = DESCRIPTOR.message_types_by_name['UpdateResponse']
_UPPERCASEREQUEST = DESCRIPTOR.message_types_by_name['UppercaseRequest']
_UPPERCASERESPONSE = DESCRIPTOR.message_types_by_name['UppercaseResponse']
_COPYREQUEST = DESCRIPTOR.message_types_by_name['CopyRequest']
_COPYRESPONSE = DESCRIPTOR.message_types_by_name['CopyResponse']
_COPYEVENTREQUEST = DESCRIPTOR.message_types_by_name['CopyEventRequest']
_COPYEVENTRESPONSE = DESCRIPTOR.message_types_by_name['CopyEventResponse']
WindowsUiaCell = _reflection.GeneratedProtocolMessageType('WindowsUiaCell', (_message.Message,), {
  'DESCRIPTOR' : _WINDOWSUIACELL,
  '__module__' : 'legacy_pb2'
  # @@protoc_insertion_point(class_scope:aspire.legacy.WindowsUiaCell)
  })
_sym_db.RegisterMessage(WindowsUiaCell)

UpdateRequest = _reflection.GeneratedProtocolMessageType('UpdateRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPDATEREQUEST,
  '__module__' : 'legacy_pb2'
  # @@protoc_insertion_point(class_scope:aspire.legacy.UpdateRequest)
  })
_sym_db.RegisterMessage(UpdateRequest)

UpdateResponse = _reflection.GeneratedProtocolMessageType('UpdateResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPDATERESPONSE,
  '__module__' : 'legacy_pb2'
  # @@protoc_insertion_point(class_scope:aspire.legacy.UpdateResponse)
  })
_sym_db.RegisterMessage(UpdateResponse)

UppercaseRequest = _reflection.GeneratedProtocolMessageType('UppercaseRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPPERCASEREQUEST,
  '__module__' : 'legacy_pb2'
  # @@protoc_insertion_point(class_scope:aspire.legacy.UppercaseRequest)
  })
_sym_db.RegisterMessage(UppercaseRequest)

UppercaseResponse = _reflection.GeneratedProtocolMessageType('UppercaseResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPPERCASERESPONSE,
  '__module__' : 'legacy_pb2'
  # @@protoc_insertion_point(class_scope:aspire.legacy.UppercaseResponse)
  })
_sym_db.RegisterMessage(UppercaseResponse)

CopyRequest = _reflection.GeneratedProtocolMessageType('CopyRequest', (_message.Message,), {
  'DESCRIPTOR' : _COPYREQUEST,
  '__module__' : 'legacy_pb2'
  # @@protoc_insertion_point(class_scope:aspire.legacy.CopyRequest)
  })
_sym_db.RegisterMessage(CopyRequest)

CopyResponse = _reflection.GeneratedProtocolMessageType('CopyResponse', (_message.Message,), {
  'DESCRIPTOR' : _COPYRESPONSE,
  '__module__' : 'legacy_pb2'
  # @@protoc_insertion_point(class_scope:aspire.legacy.CopyResponse)
  })
_sym_db.RegisterMessage(CopyResponse)

CopyEventRequest = _reflection.GeneratedProtocolMessageType('CopyEventRequest', (_message.Message,), {
  'DESCRIPTOR' : _COPYEVENTREQUEST,
  '__module__' : 'legacy_pb2'
  # @@protoc_insertion_point(class_scope:aspire.legacy.CopyEventRequest)
  })
_sym_db.RegisterMessage(CopyEventRequest)

CopyEventResponse = _reflection.GeneratedProtocolMessageType('CopyEventResponse', (_message.Message,), {
  'DESCRIPTOR' : _COPYEVENTRESPONSE,
  '__module__' : 'legacy_pb2'
  # @@protoc_insertion_point(class_scope:aspire.legacy.CopyEventResponse)
  })
_sym_db.RegisterMessage(CopyEventResponse)

_BRAIN = DESCRIPTOR.services_by_name['Brain']
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _WINDOWSUIACELL._serialized_start=31
  _WINDOWSUIACELL._serialized_end=97
  _UPDATEREQUEST._serialized_start=99
  _UPDATEREQUEST._serialized_end=147
  _UPDATERESPONSE._serialized_start=149
  _UPDATERESPONSE._serialized_end=230
  _UPPERCASEREQUEST._serialized_start=232
  _UPPERCASEREQUEST._serialized_end=269
  _UPPERCASERESPONSE._serialized_start=271
  _UPPERCASERESPONSE._serialized_end=355
  _COPYREQUEST._serialized_start=357
  _COPYREQUEST._serialized_end=410
  _COPYRESPONSE._serialized_start=412
  _COPYRESPONSE._serialized_end=512
  _COPYEVENTREQUEST._serialized_start=514
  _COPYEVENTREQUEST._serialized_end=572
  _COPYEVENTRESPONSE._serialized_start=574
  _COPYEVENTRESPONSE._serialized_end=679
  _BRAIN._serialized_start=682
  _BRAIN._serialized_end=985
# @@protoc_insertion_point(module_scope)
