# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph/table/coordinates.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x1dgraph/table/coordinates.proto\x12\x12\x61spire.graph.table\"\'\n\x0b\x43oordinates\x12\x0b\n\x03row\x18\x01 \x01(\r\x12\x0b\n\x03\x63ol\x18\x02 \x01(\rb\x06proto3')



_COORDINATES = DESCRIPTOR.message_types_by_name['Coordinates']
Coordinates = _reflection.GeneratedProtocolMessageType('Coordinates', (_message.Message,), {
  'DESCRIPTOR' : _COORDINATES,
  '__module__' : 'graph.table.coordinates_pb2'
  # @@protoc_insertion_point(class_scope:aspire.graph.table.Coordinates)
  })
_sym_db.RegisterMessage(Coordinates)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _COORDINATES._serialized_start=53
  _COORDINATES._serialized_end=92
# @@protoc_insertion_point(module_scope)
