# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: graph/table/table.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import aspire.translation.cell_pb2 as graph_dot_table_dot_cell__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x17graph/table/table.proto\x12\x12\x61spire.graph.table\x1a\x16graph/table/cell.proto\"K\n\x05Table\x12\x0b\n\x03uid\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\'\n\x05\x63\x65lls\x18\x03 \x03(\x0b\x32\x18.aspire.graph.table.Cellb\x06proto3')



_TABLE = DESCRIPTOR.message_types_by_name['Table']
Table = _reflection.GeneratedProtocolMessageType('Table', (_message.Message,), {
  'DESCRIPTOR' : _TABLE,
  '__module__' : 'graph.table.table_pb2'
  # @@protoc_insertion_point(class_scope:aspire.graph.table.Table)
  })
_sym_db.RegisterMessage(Table)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _TABLE._serialized_start=71
  _TABLE._serialized_end=146
# @@protoc_insertion_point(module_scope)
