# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: input/key.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0finput/key.proto\x12\x16\x61spire.brain.input.key\"\x12\n\x03Key\x12\x0b\n\x03key\x18\x01 \x01(\tb\x06proto3')



_KEY = DESCRIPTOR.message_types_by_name['Key']
Key = _reflection.GeneratedProtocolMessageType('Key', (_message.Message,), {
  'DESCRIPTOR' : _KEY,
  '__module__' : 'input.key_pb2'
  # @@protoc_insertion_point(class_scope:aspire.brain.input.key.Key)
  })
_sym_db.RegisterMessage(Key)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _KEY._serialized_start=43
  _KEY._serialized_end=61
# @@protoc_insertion_point(module_scope)
